function fixPNG(c,e){e||(e="scale");if(/MSIE (5\.5|6).+Win/.test(navigator.userAgent)){var k;if("IMG"==c.tagName)/\.png$/.test(c.src)&&(k=c.src,/siteUrl/.test("$siteUrl")?c.src="blank.gif":c.src="$siteUrl/blank.gif");else if(k=c.currentStyle.backgroundImage.match(/url\("(.+\.png)"\)/i))k=k[1],c.runtimeStyle.backgroundImage="none";k&&(c.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+k+"',sizingMethod='"+e+"')")}}function fixPNG_crop(c){fixPNG(c,"crop")}
window.xnextFixedMode=!0;if("BackCompat"==document.compatMode&&/MSIE .+Win/.test(navigator.userAgent)&&!/MSIE 1\d+\./.test(navigator.userAgent)||/MSIE (5\.5|6).+Win/.test(navigator.userAgent)&&!/MSIE [78]/.test(navigator.userAgent))window.xnextFixedMode=!1;function xnextScrollTop(){return document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop}
function xnextScrollLeft(){return document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft}function xnextClientWidth(){return document.documentElement.clientWidth?document.documentElement.clientWidth:document.body.clientWidth}function xnextClientHeight(){return document.documentElement.clientHeight?document.documentElement.clientHeight:document.body.clientHeight}
function xnextStickTop(c){c.style.bottom="auto";xnextFixedMode?c.style.top="0px":c.style.setExpression("top","( ignoreMe = xnextScrollTop() ) + 'px'")}function xnextStickBottom(c){var e=c.offsetHeight+xnextParseSize(c.style.marginTop)+xnextParseSize(c.style.marginBottom);xnextFixedMode?(c.style.top="auto",c.style.bottom="0px"):(c.style.bottom="auto",c.style.setExpression("top","( ignoreMe = xnextScrollTop() + xnextClientHeight() - "+e+" ) + 'px'"))}
function xnextStickLeft(c){c.style.right="auto";xnextFixedMode?c.style.left="0px":c.style.setExpression("left","( ignoreMe = xnextScrollLeft() ) + 'px'")}function xnextParseSize(c){return c&&""!=c?eval(c.replace("px","")):0}
function xnextStickRight(c){var e=c.offsetWidth+xnextParseSize(c.style.marginLeft)+xnextParseSize(c.style.marginRight);xnextFixedMode?(c.style.left="auto",c.style.right="0px"):(c.style.right="auto",c.style.setExpression("left","( ignoreMe = xnextScrollLeft() + xnextClientWidth() - "+e+" ) + 'px'"))}
Persist=function(){var c,e,k,q,l,h,g,p,r,m;m=function(){var a=["expires","path","domain"],b=escape,d=unescape,c=document,f,g=function(d,c){var n,t,g,f=[],e=2<arguments.length?arguments[2]:{};f.push(b(d)+"="+b(c));for(n=0;n<a.length;n++)t=a[n],(g=e[t])&&f.push(t+"="+g);e.secure&&f.push("secure");return f.join("; ")};f={set:function(a,b){var d=2<arguments.length?arguments[2]:{},f=new Date;f.setTime(f.getTime());var e={};d.expires&&(d.expires*=864E5,e.expires=new Date(f.getTime()+d.expires),e.expires=
e.expires.toGMTString());f=["path","domain","secure"];for(i=0;i<f.length;i++)d[f[i]]&&(e[f[i]]=d[f[i]]);d=g(a,b,e);c.cookie=d;return b},has:function(a){a=b(a);var d=c.cookie,f=d.indexOf(a+"="),d=d.substring(0,a.length);return!f&&a!=d||0>f?!1:!0},get:function(a){a=b(a);var f=c.cookie,e=f.indexOf(a+"="),g=e+a.length+1,h=f.substring(0,a.length);if(!e&&a!=h||0>e)return null;a=f.indexOf(";",g);0>a&&(a=f.length);return d(f.substring(g,a))},remove:function(a){var b=f.get(a);c.cookie=g(a,"",{expires:"Thu, 01-Jan-1970 00:00:01 GMT"});
return b},keys:function(){var a=c.cookie.split("; "),b,f,e=[];for(b=0;b<a.length;b++)f=a[b].split("="),e.push(d(f[0]));return e},all:function(){var a=c.cookie.split("; "),b,f,e=[];for(b=0;b<a.length;b++)f=a[b].split("="),e.push([d(f[0]),d(f[1])]);return e},version:"0.2.1",enabled:!1};f.enabled=function(){var a=new Date,a=a.toGMTString();this.set("__EC_TEST__",a);return this.enabled=this.remove("__EC_TEST__")==a}.call(f);return f}();r=function(){};g=function(a){return"PS"+a.replace(/_/g,"__").replace(/ /g,
"_s")};e=["localstorage","whatwg_db","globalstorage","ie","flash"];k=/^[a-z][a-z0-9_ -]+$/i;q="init get set remove load save".split(" ");c={autostart:!0};h={whatwg_db:{size:204800,test:function(){if(!window.openDatabase||!window.openDatabase("PersistJS Test","1","Persistent database test.",h.whatwg_db.size))return!1;try{h.localstorage.test()}catch(a){if(DOMException&&a.code==DOMException.QUOTA_EXCEEDED_ERR)return!1}return!0},methods:{transaction:function(a){this.db_created||this.db.transaction(function(a){a.executeSql("CREATE TABLE IF NOT EXISTS persist_data (k TEXT UNIQUE NOT NULL PRIMARY KEY, v TEXT NOT NULL)",
[],function(){this.db_created=!0})},r);this.db.transaction(a)},init:function(){this.db=openDatabase(this.name,"1",this.o.about||"Persistent storage for "+this.name,this.o.size||h.whatwg_db.size)},get:function(a,b,d){b&&(d=d||this,this.transaction(function(c){c.executeSql("SELECT v FROM persist_data WHERE k = ?",[a],function(a,c){0<c.rows.length?b.call(d,!0,c.rows.item(0).v):b.call(d,!1,null)})}))},set:function(a,b,d,c){this.transaction(function(f){f.executeSql("DELETE FROM persist_data WHERE k = ?",
[a],function(){f.executeSql("INSERT INTO persist_data(k, v) VALUES (?, ?)",[a,b],function(a,f){d&&d.call(c||this,!0,b)})})});return b},remove:function(a,b,d){sql="DELETE FROM persist_data WHERE k = ?";this.transaction(function(c){b?c.executeSql("SELECT v FROM persist_data WHERE k = ?",[a],function(c,e){if(0<e.rows.length){var n=e.rows.item(0).v;c.executeSql(sql,[a],function(a,c){b.call(d||this,!0,n)})}else b.call(d||this,!1,null)}):c.executeSql(sql,[a])})}}},globalstorage:{size:5242880,test:function(){return window.globalStorage&&
window.globalStorage[location.hostname]?!0:!1},methods:{key:function(a){return g(this.name)+g(a)},init:function(){this.store=globalStorage[this.o.domain]},get:function(a,b,d){a=this.key(a);b&&b.call(d||this,!0,this.store.getItem(a))},set:function(a,b,d,c){a=this.key(a);this.store.setItem(a,b);d&&d.call(c||this,!0,b)},remove:function(a,b,d){var c;a=this.key(a);c=this.store[a];this.store.removeItem(a);b&&b.call(d||this,null!==c,c)}}},localstorage:{size:-1,test:function(){return window.localStorage?
(window.localStorage.setItem("test_localstorage_key","test_localstorage_value"),!0):!1},methods:{key:function(a){return g(this.name)+g(a)},init:function(){this.store=localStorage},get:function(a,b,d){a=this.key(a);b&&b.call(d||this,!0,this.store.getItem(a))},set:function(a,b,d,c){a=this.key(a);/(iPad|iPod|iPhone)/.test(navigator.userAgent)&&this.store.removeItem(a);this.store.setItem(a,b);d&&d.call(c||this,!0,b)},remove:function(a,b,d){var c;a=this.key(a);c=this.getItem(a);this.store.removeItem(a);
b&&b.call(d||this,null!==c,c)}}},ie:{prefix:"_persist_data-",size:65536,test:function(){if(window.ActiveXObject){if(!/MSIE [67].+Win/.test(navigator.userAgent))return!1;var a=g("test_ie_storage"),a=h.ie.make_userdata(a);a.setAttribute("test_key","test-ecwid");try{return"test-ecwid"==a.getAttribute("test_key")}catch(b){}}return!1},make_userdata:function(a){var b=document.createElement("div");b.id=a;b.style.display="none";b.addBehavior("#default#userData");document.body.appendChild(b);return b},methods:{init:function(){var a=
h.ie.prefix+g(this.name);this.el=h.ie.make_userdata(a);this.o.defer&&this.load()},get:function(a,b,c){a=g(a);this.o.defer||this.load();a=this.el.getAttribute(a);b&&b.call(c||this,a?!0:!1,a)},set:function(a,b,c,e){a=g(a);this.el.setAttribute(a,b);this.o.defer||this.save();c&&c.call(e||this,!0,b)},load:function(){try{this.el.load(g(this.name))}catch(a){window.console&&window.console.log("Could not load user data: "+a),this.el.save(g(this.name))}},save:function(){this.el.save(g(this.name))}}},cookie:{delim:":",
size:4E3,test:function(){return l.Cookie.enabled?!0:!1},methods:{key:function(a){return this.name+h.cookie.delim+a},get:function(a,b,c){a=this.key(a);val=m.get(a);b&&b.call(c||this,null!=val,val)},set:function(a,b,c,e){a=this.key(a);m.set(a,b,this.o);c&&c.call(e||this,!0,b)},remove:function(a,b,c,e){a=this.key(a);b=m.remove(a);c&&c.call(e||this,null!=b,b)}}},flash:{test:function(){return window.SWFObject&&deconcept&&deconcept.SWFObjectUtil?8<=deconcept.SWFObjectUtil.getPlayerVersion().major?!0:!1:
!1},methods:{init:function(){if(!h.flash.el){var a,b,d;d=document.createElement("div");d.id="_persist_flash_wrap";document.body.appendChild(d);a=new SWFObject(this.o.swf_path||"persist.swf","_persist_flash",1,1,"8");for(b in c)a.addVariable(b,c[b]);a.write(d);h.flash.el=document.getElementById("_persist_flash")}this.el=h.flash.el},get:function(a,b,c){a=g(a);a=this.el.get(this.name,a);b&&b.call(c||this,null!==a,a)},set:function(a,b,c,e){a=g(a);this.el.set(this.name,a,b);c&&c.call(e||this,!0,b)},remove:function(a,
b,c){a=g(a);a=this.el.remove(this.name,a);b&&b.call(c||this,!0,a)}}}};p=function(){var a,b,c,g,f=e;a=0;for(b=q.length;a<b;a++)l.Store.prototype[q[a]]=r;l.type=null;l.size=-1;a=0;for(b=f.length;!l.type&&a<b;a++){c=h[f[a]];var k=!1;try{window.console&&window.console.log("Trying persistent storage backend: "+f[a]),k=c.test(),window.console&&window.console.log("Success: "+k)}catch(m){window.console&&window.console.log(m)}if(k)for(g in l.type=f[a],l.size=c.size,c.methods)l.Store.prototype[g]=c.methods[g]}l._init=
!0};l={VERSION:"0.1.0",type:null,size:0,add:function(a){h[a.id]=a;e=[a.id].concat(e);p()},remove:function(a){var b=e.indexOf(a);0>b||(e.splice(b,1),delete h[a],p())},Cookie:m,Store:function(a,b){if(!k.exec(a))throw Error("Invalid name");if(!l.type)throw Error("No suitable storage found");b=b||{};this.name=a;b.domain=b.domain||location.hostname||"localhost.localdomain";this.o=b;b.expires=b.expires||730;b.path=b.path||"/";this.init()}};p();return l}();
